### ISSUE TITLE
Updates needed for BGM reversion

### ISSUE THREAD

**Issue by ItaloKnox** [07th-mod/python-patcher#133]
Everything is pretty much ready for the BGM reversion stuff, but I need some stuff changed (preferably by a PR that I can merge before I release the patches).

What we need to do:
- add a new BGM and SFX section in versionData for both question and answer arcs
- remove BGM and SFX optional downloads section from both question and answer arcs
    - Question Arcs should install the current optional BGM and SFX by default
    - Answer Arcs should install the tailored BGM packs ([this commit](https://github.com/07th-mod/wiki/commit/d36e5a0b9f1d3f3ac49dabc927bf58ab5c00db1c#diff-6108f566cfa2bc24b6d809bd62ec8741f957647dcdc9835f2989ea641eed4c9c)) + current optional SFX
        - cases where the chapter don't get a tailored pack will be rectified later on

**Comment by drojf** [comment]
the packs won't work properly with the voice only patches right? since there are script changes

**Comment by ooa113y** [comment]
Are we still providing the VO patches in the installer? Might be best to just rip them out entirely at this point, their reason for existence is now effectively null as we have full support for original graphics in the main patch.

**Comment by ItaloKnox** [comment]
> the packs won't work properly with the voice only patches right? since there are script changes

Answer Arcs won't, but you can do the same thing as the question arcs (force optional bgm and sfx) if you want.

> Are we still providing the VO patches in the installer? Might be best to just rip them out entirely at this point, their reason for existence is now effectively null as we have full support for original graphics in the main patch.

Agreed. I also would go as far as enabling the experimental DLL by default. Just change the option to allow the user to opt-out or something like that. If we get all the testing we need, the Voices-only patches can die asap.

**Comment by drojf** [comment]
Alright, I have made [a pull request which will add the BGM/SFX reversion stuff](https://github.com/07th-mod/python-patcher/pull/134), and also make the DLL the default:

Let me know if everything seems OK/when you want to push this out.

**Comment by ItaloKnox** [comment]
Looks great, I'll prepare the releases for later today (it's 1AM here so... in about 15 hours).

**Comment by drojf** [comment]
As someone pointed out on discord, the Wiki hasn't been updated to reflect the BGM changes (to say it's installed by default etc...). Probably need to update:
- [ ] Intro page (currently says "Optionally Revert to old Higurashi soundtrack and sound effects") https://07th-mod.com/wiki/Higurashi/Higurashi-Getting-started/
- [ ] Manual Installation page - some changes have already been made here: https://github.com/07th-mod/wiki/pull/21 , but also Need to update the "Optional Downloads" section
- [ ] Not related to the BGM/SE, but I also need to update the Shortcuts and Settings page and FAQ for the new DLL

Also, we forgot to update the `versionData.json` for the new scripts, but thankfully FatesTimelines1337 caught it here: https://github.com/07th-mod/python-patcher/pull/135 . I merged it a little while ago, so that should be sorted now.

**Comment by ItaloKnox** [comment]
Welp, sorry. I had a PR up for this and forgot to merge it. Looks like someone already did it, though.

I'll take a look at whatever can be done better.

**Comment by drojf** [comment]
Currently there are 4 different BGM packs for the answer arcs (one for each chapter). 

I asked GIN about this, and compared the files on disk, and it appears that these can be merged together (as none of the files conflict with each other), so we can just have one "Answer Arcs" BGM pack (which will cost a small amount of disk space, between 6 and 38mb per chapter)

GIN also mentioned that it would be easier if we want to add BGM to the script, since we wouldn't need to check which BGM is present in which chapter's BGM pack.

- [ ] Merge BGM packs together
- [ ] Update versionData
- [ ] Update installData

**Comment by drojf** [comment]
I think this issue can be closed now.

The only other thing remaning for the BGM/SE is to make it switchable in-game via the DLL. I found the original issue for that: https://github.com/07th-mod/higurashi-patch-compiler/issues/56 - further work/discussion should be in that issue or in the DLL repository
