### ISSUE TITLE
Automatic Umineko Hane detection issues

### ISSUE THREAD

**Issue by FatesTimelines1337** [07th-mod/python-patcher#142]
Selecting to install Umineko Hane while there is a game install of Ciconia Phase 1 installed results in the mod installer autodetecting the Ciconia install path when it is not supposed to.

**Comment by ooa113y** [comment]
I think I know why this happens... The "executable" the installer looks for is `pscript.dat` -- a file that's present in the Saku versions of the Umineko games but not in the original releases -- I specifically chose it for that reason so that people wouldn't try to install on top of the old Hane release. I can't really use the .exe because Saku ships with a non-Unicode based installer, causing the exe filename to come out mangled in varying ways depending on your system locale...
However, Ciconia also ships with this file. I haven't really considered this because I forgot the autodetection exists.
This issue will kinda resolve itself when Saku is released on Steam and we have the "real" executable names, but in the meantime, @drojf, is there an easy way to remove autodetection for the `umineko_nscripter` mod family? It could be useful for a while.

**Comment by drojf** [comment]
I added an optional "autodetect" field to each mod in the `installData.json`, which defaults to true. I set Hane to "autodetect: false" so it does not autodetect.

Is that OK for this issue, or should I actually disable the other `umineko_nscripter` games as well?

**Comment by ooa113y** [comment]
I've added it for the other games as well -- as of right now, these will not ever be in a path where autodetection is possible. I'll roll this back when the Steam version comes out. Merge the branch when it's ready (I'm not sure if it is).

**Comment by drojf** [comment]
Should be fixed in https://github.com/07th-mod/python-patcher/releases/tag/v1.1.77

I squashed the commits so the git history is cleaner into 19155b1

**Comment by ooa113y** [comment]
I'm reopening this as these fixes actually broke manual selection, rendering the installation for Saku content completely unusable. @drojf please take another look when you can.

**Comment by ooa113y** [comment]
Fully fixed in aad278c.
