### ISSUE TITLE
Installer is getting stuck on a mod install

### ISSUE THREAD

**Issue by FatesTimelines1337** [07th-mod/python-patcher#217]
When selecting a patch to install, then selecting another patch to install, the installer will get stuck wanting to install the first patch over the location where the second patch goes.

[07th-mod-logs.zip](https://github.com/07th-mod/python-patcher/files/12330616/07th-mod-logs.zip)

**Comment by drojf** [comment]
Do you mean how the "console arcs" installs to chapter 4? because that's intentional - the console arcs installs to ch.4 (as there is no 'unmodded' console arcs release, we just picked the most recent chapter at the time). But for all other chapters, the mod should install to the game with the same name.

I reviewed your logs and everything looks correct - perhaps show a screenshot of the issue? Or more detailed reproduction steps.

**Comment by FatesTimelines1337** [comment]
<img width="580" alt="Screenshot 2023-08-14 at 9 58 10 AM" src="https://github.com/07th-mod/python-patcher/assets/38626341/85ee4401-9b0f-436c-b80a-ca34b638c297">

So, select the chapter 7 patch, then go to the chapter 6 patch. For some reason, it wants to install the chapter 7 patch instead.

**Comment by FatesTimelines1337** [comment]
It appears to have been caused by a change made between [v1.2.20](https://github.com/07th-mod/python-patcher/tree/v1.2.20) and [v1.2.21](https://github.com/07th-mod/python-patcher/tree/v1.2.21)

**Comment by drojf** [comment]
Sorry, I'm not sure how I wasn't able to reproduce it earlier, but I can see the bug now...

It looks like it's caused by this commit: https://github.com/07th-mod/python-patcher/commit/fb82b1979ad86ad9d4f958d2c1e33d854e402b41

I'll publish a fixed release shortly and you can double check it fixes it

**Comment by drojf** [comment]
Ok, please test https://github.com/07th-mod/python-patcher/releases/tag/v1.2.22 to see if it is fixed

**Comment by FatesTimelines1337** [comment]
It's fixed

**Comment by drojf** [comment]
Thanks for reporting this bug, I can imagine it causing heaps of issues
