### ISSUE TITLE
Installer can be stuck at the 'validating...' step and fail to validate a valid, already modded higu path

### ISSUE THREAD

**Issue by enumag** [07th-mod/python-patcher#42]
Clicked the button, installer kept saying "Validating..." indefinitely.

**Comment by Grelo** [comment]
When i did a fresh install of the game it fixed this issue.

**Comment by drojf** [comment]
Installer can fail on a valid, already modded (maybe installed manually) higurashi install,

I think either it crashed or looped infinitely, something like that, while scanning the path, so the 'validating...' message would be continously displayed

**Comment by drojf** [comment]
I haven't seen this reported for a long time. I also added a check so that if the web GUI loses connection with the terminal (the server), or the server crashes etc., a orange toast notification will be shown. That's about the only time that this could happen, so hopefully it should make the issue more obvious if it does happen, rather than just saying "Validating...."
