### ISSUE TITLE
MacOS: SSL Error during "Querying URLs" stage of installation

### ISSUE THREAD

**Issue by Johnson8396** [07th-mod/python-patcher#60]
I am a mac user, and after I select the path for the installation on the cross-platform installer, I am getting this as an error message:

07th Mod - Install failed due to error: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>

I'm not sure what it means. Let me know if there is anything I can do, thank you!

**Comment by drojf** [comment]
hi, which version of MacOS are you using?

**Comment by drojf** [comment]
If you could provide your install logs in the install_data\LOGS folder, that would be useful too.

**Comment by Johnson8396** [comment]
wow, that was a quick response, I am using Sierra version 10.12.6

**Comment by drojf** [comment]
Also if you're using some sort of proxy or VPN, that can sometimes interfere. You might be using a proxy unknowingly if you're at a business or school.

**Comment by Johnson8396** [comment]
I'm at home, and I don't often mess around with my network so I don't think it is a proxy or a VPN but Im not 100% sure. Here is a zip file with the install logs:

[07th-mod-logs.zip](https://github.com/07th-mod/python-patcher/files/3220175/07th-mod-logs.zip)

**Comment by drojf** [comment]
This won't fix your issue properly, but will at least let you install the game (assuming you downloaded the v0.0.44 installer - version is displayed at bottom of the screen of each page).

1. Download this zip: [main.zip](https://github.com/07th-mod/python-patcher/files/3220199/main.zip)
2. Extract it, giving you two files: main.py and installData.json
3. Open the `install_data` folder in the installer, and replace the `main.py` and `installData.json`. with the above two files
4. Run the installer again.

Again, this is just a workaround - if you download another installer a month in the future doing this might not work.

(We made some changes to the umineko installer just today, it would be great if you could confirm the voices work properly after it installs, assuming it works)

**Comment by drojf** [comment]
**For developers only**

See this issue: https://github.com/kennethreitz/requests/issues/3340
And this issue: https://superuser.com/questions/1092508/sslv3-alert-handshake-failure-ssl-c590

You can verify which TLS/SSL our server supports here: https://www.cdn77.com/tls-test (and type in 07th-mod). Our server doesn't support SSL, only TLS (which is normally a good thing, see https://disablessl3.com/).

The reason the installer gets past the 'check connection with server' stage is because the server check uses a non-secure `http://...` connection, not `https://`. We could either add instructions on how to update their SSL version, or just use insecure links if the user enables it :S. Could also allow SSL on the 07th mod server

@tellowkrinkle

**Comment by Johnson8396** [comment]
When I look into the install_data folder in the 0.0.44 installer I see a main.py file that I can replace but I don't see a installdata.json file to replace. Let me know if I should be seeing one or if there is some other file I may have to replace. Thank you so much for all the help, andI will be sure to let you know how the voices are working!

**Comment by drojf** [comment]
sorry, you are correct. Just put the `installData.json` in there - it shouldn't replace anything -_-

**Comment by Johnson8396** [comment]
Alright! I got it downloaded by following your instructions, and everything looks great ADV mode was exactly what I was looking for, and the voices sound clear and beautiful!!! Thanks again!!

**Comment by drojf** [comment]
No problem! Please leave this issue open as we haven't actually resolved the issue yet. You can press 'ignore notifications on the right' if you don't want further messages on this log

**Comment by tellowkrinkle** [comment]
We shouldn't need to enable SSLv3

[Here](https://www.ssllabs.com/ssltest/analyze.html?d=raw.githubusercontent.com&s=151.101.0.133) is GitHub's SSL support (which they are able to use)
And [here](https://www.ssllabs.com/ssltest/analyze.html?d=07th%2dmod.com&s=104.27.185.163) is ours (which has a handshake failure for OpenSSL 0.9.8)

It looks like we just need to support one of the cipher suites listed [here](https://www.ssllabs.com/ssltest/viewClient.html?name=OpenSSL&version=0.9.8y&key=27), GitHub ends up using `TLS_RSA_WITH_AES_128_CBC_SHA`

**Comment by drojf** [comment]
I had a quick look into it and...I have no idea what I'm doing.

Also, in the 'ours' link, it states Cloudflare rather than our website. I'm not sure if I don't understand it correctly, but if it is Cloudflare serving the files then I don't know if we can change what ciphers it supports. Here is cloudflare's page about what ciphers it supports: https://support.cloudflare.com/hc/en-us/articles/203041594-Cloudflare-SSL-cipher-browser-and-protocol-support

If it's our server we should be able to do something about it ... but I don't know how to do it.

@ItaloKnox is this something you know how to do or are familiar with?

----

Currently the only 'important' urlopen calls are used to get the filename of each file. If we can get around that then we don't need to use urlopen at all. The initial download of the installData.json can be done using aria2c as well.

cURL has a flag which lets you specifically download just the headers, which we could use.

Again, this is just another alternative - fixing it the other way by just enabling the cipher is way easier.

**Comment by tellowkrinkle** [comment]
Actually since we just need this to get filenames I don't see any reason we need HTTPS, we can just make it swap the URLs to HTTP on old openssl versions

**Comment by drojf** [comment]
I thought about that a little bit before - for some reason I thought it would be a problem because the redirect link could be malicious, but since we don't even use the redirect URL afterwards (we make aria2c re-query the URL from scratch) it's not a problem.

I'll try implementing it since it seems easy enough. I guess I'll do something like:

1. Modify the initial query on startup of the 07th-mod server to be HTTPS. If it passes, proceed as normal.
2. If the query fails, then try again using the HTTP url. If it passes, then activate 'old OpenSSL mode'. If it fails, assume no connection with the 07th mod server and show an error.
3. Use the previously set mode to determine how the URLs will be queried.

**Comment by tellowkrinkle** [comment]
I'll set it up
