### ISSUE TITLE
resS files in UI mod

### ISSUE THREAD

**Issue by enumag** [07th-mod/python-patcher#62]
The `sharedassets0.assets.resS` files are never changed in the UI mod so next versions of the UI packs will no longer contain them. Make sure the installer does not rename the vanilla file to `sharedassets0.assets.resS.backup`.

**Comment by enumag** [comment]
Note that you can do this change right away. It does not matter for Oni and Wata and all other chapters have their UI mod completely broken now anyway. Tellow is already working on a fix for that.

**Comment by drojf** [comment]
hmm....when I installed the other day I didn't get a .resS.backup file, and the backup function doesn't appear to create one (see below)

https://github.com/07th-mod/python-patcher/blob/fc89e8a87f81ba7834cd6c84a9674b96f7b45bc4/higurashiInstaller.py#L77-L84

It looks like the old installer (which is now removed) did create the .resS.backup files - perhaps that's where it was coming from?

Here's the commit where I've removed the old installer, where you can see the .resS.backup files being created: https://github.com/07th-mod/resources/commit/b2312d546685045fbfc73ea32a3e315bdc056f3e

**Comment by enumag** [comment]
I see. In that case it seems to be already implemented.

Can you confirm to me that the `sharedassets0.assets.resS` file from the downloaded archive is never used?

**Comment by drojf** [comment]
As far as I understand it, all the archives are treated the same way for higurashi:
1. archives are extracted into the root of the "[GAME_NAME] Extraction" directory (producing a HigurashiEp0X folder, and the game exe(s), if present)
2. the HigurashiEp0X folder and game exe for your system are moved into the real game folder (overwriting the existing HigurashiEp0X folder in the real game folder)

Because it just moves the whole HigurashiEp0X folder, any file included in the archive which is inside that folder will always go into the game directory. So yes it is used during extraction, but that doesn't mean it's actually necessary.

I guess you'll need to discuss with @tellowkrinkle on this one.

Here is the moveFilesIntoPlace() function which does the move operation I mentioned above
https://github.com/07th-mod/python-patcher/blob/fc89e8a87f81ba7834cd6c84a9674b96f7b45bc4/higurashiInstaller.py#L122-L141

**Comment by enumag** [comment]
Ah ok so it is used but only because it is in the archive - it's not required to be there. That's just fine, we can close this then. Thanks!

**Comment by tellowkrinkle** [comment]
Can confirm that this is how it works
