### ISSUE TITLE
Could not connect to host 127.0.0.1: Connection Refused

### ISSUE THREAD

**Issue by afromanDAN** [07th-mod/python-patcher#70]
[MOD-INSTALLER-LOG-2019-07-21_00-53-05.txt](https://github.com/07th-mod/python-patcher/files/3414343/MOD-INSTALLER-LOG-2019-07-21_00-53-05.txt)
Hello, I am having this issue when running the installer on arch linux using KDE>
![image](https://user-images.githubusercontent.com/20655561/61587623-184f5b80-ab53-11e9-9b10-143449490c7a.png)

**Comment by drojf** [comment]
Here is a new version of the installer which attempts to fix the issue: https://github.com/07th-mod/python-patcher/releases/tag/v0.0.61

Let me know if it works (the web GUI should open in your browser instead of this error)

If it does not fix the issue, please try the below instructions: 

----

If you hit "OK" despite the error, keep the terminal window open, then manually navigate to the URL shown in the terminal, does the web GUI open?

You must look at the port specified in the terminal - **the port is different each time the program runs**. 
If you just copy and paste the url shown (`http://127.0.0.1:<PORT>`) in the terminal into your browser that should work too.

I suspect it's just the method we're using to open your browser is not working, so if you manually open the page in your browser it might work (it looks like the PORT part is cut-off in the error message).

Also, which version of python do you have installed?

**Comment by afromanDAN** [comment]
I can confirm that this fixed my issue. Thanks!
