### ISSUE TITLE
Add instructions for obtaining the installer/logs

### ISSUE THREAD

**Issue by drojf** [07th-mod/python-patcher#90]
It would be nice to have a short description of where to find the game/install logs all in one place on the wiki, to make troubleshooting easier.

Need to describe:
- The location on each platform (win, linux, mac), if it's different
- The location for the installer (or which button to press to open it)
- The location for Umineko and Higurashi games.

Add screenshots to give user context so it's easier to find the folder/files.

**Comment by ItaloKnox** [comment]
I've been on the fence for a while about suggesting a few changes to the [installer snippet](https://github.com/07th-mod/wiki/blob/master/docs/Snippets/Cross-Platform-Installer.md). I believe a lot of information could be moved into a separate category below Umineko in the sidebar and only the bare minimum used as snippet, such as the instructions and maybe where to go next in case things do not work as expected. I can work on these changes if you want.

**Comment by drojf** [comment]
Sure, I've just been stuffing common errors into the bottom of the page...Certainly that could be its own page.

I'm also uncertain how many people use the information under the "Power Users" tab, perhaps that could be moved (or put in a developer section)

**Comment by ItaloKnox** [comment]
I'll create a new branch tomorrow and start working on it. I won't hold back on the cosmetic changes, after that we can iterate and see what we'll keep and what we won't.

**Comment by ItaloKnox** [comment]
Looks like the changes were all minor overall, just lots of moving. I'm stuck when it comes to the theme of this issue, since I don't know much about the installer. [This page](https://github.com/07th-mod/wiki/blob/installer-update/docs/Installer/support.md) should be the last bit before it can be pushed into master.

Also, worth noting that I referenced links internally, which is something that we don't do in the wiki. Your call if you want to keep it like this (``../Instaler/support.md``) or if you want to convert them to ``07th-mod.com/wiki``. Not sure if they will break under the domain, so I just made sure all links would work when serving locally for now.

**Comment by drojf** [comment]
I'll check it out later tonight...or later tomorrow night. And fill in the page you mentioned with the install log information.

I normally prefer relative links, but I also don't know if they will break/if there was a reason we used full links earlier. If you used relative links, I guess we just try it out and see if it works.

**Comment by ItaloKnox** [comment]
Supposing the links don't break or anything we should stick with it. I can go searching for more links later after we make sure it works as intended. That's actually better in the long run since Github will probably outlive our server/domain.

**Comment by drojf** [comment]
I've somewhat merged all the support things into a "Support" checklist which has been in use for a month or so: https://github.com/07th-mod/wiki/blob/master/docs/Snippets/support-checklist.md

I also made the discord bot PM new support asking users asking them to fill in the support checklist.
